// Combo configs
#define COMBO_SHOULD_TRIGGER
#define COMBO_ONLY_FROM_LAYER 0

#define ENABLE_COMPILE_KEYCODE

#define ONESHOT_TIMEOUT 500

// Mouse configs
#define MOUSEKEY_INTERVAL    20
#define MOUSEKEY_DELAY       0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED   4
#define MOUSEKEY_WHEEL_DELAY 0

