#pragma once

#define PMW33XX_CS_PIN GP17
// #define PMW33XX_CS_PINS CS
// #define PMW33XX_CS_PIN_RIGHT CS
// #define PMW33XX_CS_PIN_LEFT CS
// #define PMW33XX_CPI CS
// #define PMW33XX_CLOCK_SPEED CS
// #define PMW33XX_SPI_DIVISOR CS
// #define PMW33XX_LIFTOFF_DISTANCE CS
// #define ROTATIONAL_TRANSFORM_ANGLE CS
// #define POINTING_DEVICE_MOTION_PIN CS
// #define POINTING_DEVICE_MOTION_PIN_ACTIVE_LOW CS
#define POINTING_DEVICE_CS_PIN GP17
// #define POINTING_DEVICE_SDIO_PIN CS
#define POINTING_DEVICE_SCLK_PIN GP18

#define SPI_DRIVER SPID0
// #define SPI_SCK_PIN GP18
#undef SPI_MISO_PIN
#define SPI_MISO_PIN GP16
#define SPI_MOSI_PIN GP19
// #define ROTATIONAL_TRANSFORM_ANGLE CS
//
#define POINTING_DEVICE_DEBUG
