#define KP_1 KC_KP_1
#define KP_2 KC_KP_2
#define KP_3 KC_KP_3
#define KP_4 KC_KP_4
#define KP_5 KC_KP_5
#define KP_6 KC_KP_6
#define KP_7 KC_KP_7
#define KP_8 KC_KP_8
#define KP_9 KC_KP_9
#define KP_0 KC_KP_0
#define KP_SLASH KC_KP_SLASH
#define KP_STAR KC_KP_ASTERISK
#define KP_MINUS KC_KP_MINUS
#define KP_PLUS KC_KP_PLUS
#define KP_EQUL KC_KP_EQUAL
#define KP_DOT KC_KP_DOT
#define KP_ENTR KC_KP_ENTER
